#!/usr/bin/with-contenv bash

export WEBHOOK_AUTH="${WEBHOOK_AUTH:-no}"
export WEBHOOK_TOKEN_NAME="${WEBHOOK_TOKEN_NAME:-4UTH}"

export HAPROXY_http_req_rate=${HAPROXY_http_req_rate:-10s}
export HAPROXY_http_req_expire=${HAPROXY_http_req_expire:-30s}
export HAPROXY_http_req_count=${HAPROXY_http_req_count:-20}

mkdir -p /app /config/{scripts,hooks} /var/run/haproxy/ /var/lib/haproxy/ 

if [ -n "$CACERT_PATH" ] && [ -f "$CACERT_PATH" ]; then
   echo "$(date -I'seconds') [INFO] Adding cacert .. "
   mv "$CACERT_PATH" /usr/local/share/ca-certificates/
   /usr/sbin/update-ca-certificates
else 
   echo "$(date -I'seconds') [INFO] No cacert detected .."
fi

if [ "$WEBHOOK_AUTH" == "yes" ]; then
   echo "$(date -I'seconds') [INFO] Hook auth enabled .. "
   cp /defaults/hooks.yaml.auth_tmpl /defaults/hooks.yaml
else 
   echo "$(date -I'seconds') [INFO] Hook auth disabled .. "
   cp /defaults/hooks.yaml.noauth_tmpl /defaults/hooks.yaml
fi

if [ ! -n "$WEBHOOK_TOKEN_VALUE" ]; then
  echo "$(date -I'seconds') [INFO] Generating webhook token .."
  export WEBHOOK_TOKEN_VALUE=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
  echo "$(date -I'seconds') [INFO] Token: $WEBHOOK_TOKEN_VALUE"
fi

if [ -n "$APPRISE_CONFIG_PATH" ] && [ -f "$APPRISE_CONFIG_PATH" ]; then
     export WEBHOOK_CONFIGURATION+="-c $APPRISE_CONFIG_PATH"
elif [ -n "$APPRISE_ENDPOINTS" ]; then
     export WEBHOOK_CONFIGURATION+="$APPRISE_ENDPOINTS"
else
  echo "$(date -I'seconds') [ERROR] APPRISE_CONFIG_PATH nor APPRISE_ENDPOINTS are valid .."
  exit 1
fi

# env for haproxy
unset IFS; for var in ${!HAPROXY_*}; do printf '%s' "${!var}" > "/var/run/s6/container_environment/$var"; done

# env for webhook
unset IFS; for var in ${!WEBHOOK_*}; do printf '%s' "${!var}" > "/var/run/s6/container_environment/$var"; done

[[ ! -f /etc/haproxy/haproxy_default.cfg ]] && \
	cp /defaults/haproxy.cfg /etc/haproxy/haproxy_default.cfg

[[ ! -f /config/scripts/notify ]] && \
	cp /defaults/notify /config/scripts/notify
   
[[ ! -f /config/hooks/hooks.yaml ]] && \
	cp /defaults/hooks.yaml /config/hooks/hooks.yaml   

chown abc:abc -R /config /var/lib/haproxy/ /var/run/haproxy/
