#!/usr/bin/with-contenv bash

export WEBHOOK_AUTH="${WEBHOOK_AUTH:-no}"
export WEBHOOK_TOKEN_NAME="${WEBHOOK_TOKEN_NAME:-4UTH}"

export HAPROXY_timeout=foo
export HAPROXY_limit=bar

mkdir -p /app /config/{scripts,hooks}

if [ -n "$CACERT_PATH" ] && [ -f "$CACERT_PATH" ]; then
   echo "$(date -I'seconds') [INFO] Adding cacert .. "
   mv "$CACERT_PATH" /usr/local/share/ca-certificates/
   /usr/sbin/update-ca-certificates
else 
   echo "$(date -I'seconds') [INFO] No cacert detected .."
fi

if [ "$WEBHOOK_AUTH" == "yes" ]; then
   echo "$(date -I'seconds') [INFO] Hook auth enabled .. "
   ln -s /config/hooks/hooks.yaml.auth_tmpl /config/hooks/hooks.yaml
else 
   echo "$(date -I'seconds') [INFO] Hook auth disabled .. "
   ln -s /config/hooks/hooks.yaml.noauth_tmpl /config/hooks/hooks.yaml
fi

if [ ! -n "$WEBHOOK_TOKEN_VALUE" ]; then
  echo "$(date -I'seconds') [INFO] Generating webhook token .."
  export WEBHOOK_TOKEN_VALUE=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
  echo "$(date -I'seconds') [INFO] Token: $WEBHOOK_TOKEN_VALUE"
fi

if [ -n "$APPRISE_CONFIG_PATH" ] && [ -f "$APPRISE_CONFIG_PATH" ]; then
     export CONFIGURATION="-c $APPRISE_CONFIG_PATH"
elif [ -n "$APPRISE_ENDPOINTS" ]; then
     export CONFIGURATION="$APPRISE_ENDPOINTS"
else
  echo "$(date -I'seconds') [ERROR] APPRISE_CONFIG_PATH nor APPRISE_ENDPOINTS are valid .."
  exit 1
fi

# env for haproxy
unset IFS; for var in ${!HAPROXY_*}; do printf '%s' "${!var}" > "/var/run/s6/container_environment/$var"; done

# env for webhook
unset IFS; for var in ${!WEBHOOK_*}; do printf '%s' "${!var}" > "/var/run/s6/container_environment/$var"; done

chown abc:abc -R /config /var/lib/haproxy/
